"""Контракты между слоями пайплайна.

Каждый слой имеет один вход и один выход, и оба описаны здесь. Слои не
обращаются во внутренности друг друга — только через эти модели.
"""

from deckwright.schemas.common import (
    EMU_PER_INCH,
    EMU_PER_POINT,
    Align,
    Box,
    Color,
    Provenance,
    SourceKind,
    TextStyle,
    VAlign,
)
from deckwright.schemas.content_pack import (
    Brief,
    ContentPack,
    DeckPurpose,
    Fact,
    NumericPoint,
    Quote,
    Series,
    SourceDoc,
)
from deckwright.schemas.deck_plan import (
    BlockKind,
    ContentBlock,
    DeckPlan,
    SlideIntent,
    SlidePlan,
)
from deckwright.schemas.issue import (
    AuditReport,
    CheckKind,
    FixKind,
    Issue,
    IssueCategory,
    ProposedFix,
    Severity,
)
from deckwright.schemas.manifest import (
    FontSubstitution,
    ModelUsage,
    PromptVersion,
    RunManifest,
    StageTiming,
)
from deckwright.schemas.slide_ir import (
    ChartContent,
    ChartKind,
    ChartSeries,
    DeckIR,
    Element,
    ElementKind,
    ImageContent,
    Paragraph,
    ShapeContent,
    SlideIR,
    TableContent,
    TextContent,
)
from deckwright.schemas.template_spec import (
    ColorToken,
    FontToken,
    Grid,
    LayoutSpec,
    Pattern,
    PatternClass,
    RecurringElement,
    Repeater,
    Slot,
    SlotRole,
    TemplateSpec,
)

__all__ = [
    "EMU_PER_INCH",
    "EMU_PER_POINT",
    "Align",
    "AuditReport",
    "BlockKind",
    "Box",
    "Brief",
    "ChartContent",
    "ChartKind",
    "ChartSeries",
    "CheckKind",
    "Color",
    "ColorToken",
    "ContentBlock",
    "ContentPack",
    "DeckIR",
    "DeckPlan",
    "DeckPurpose",
    "Element",
    "ElementKind",
    "Fact",
    "FixKind",
    "FontSubstitution",
    "FontToken",
    "Grid",
    "ImageContent",
    "Issue",
    "IssueCategory",
    "LayoutSpec",
    "ModelUsage",
    "NumericPoint",
    "Paragraph",
    "Pattern",
    "PatternClass",
    "PromptVersion",
    "ProposedFix",
    "Provenance",
    "Quote",
    "RecurringElement",
    "Repeater",
    "RunManifest",
    "Series",
    "Severity",
    "ShapeContent",
    "SlideIR",
    "SlideIntent",
    "SlidePlan",
    "Slot",
    "SlotRole",
    "SourceDoc",
    "SourceKind",
    "StageTiming",
    "TableContent",
    "TemplateSpec",
    "TextContent",
    "TextStyle",
    "VAlign",
]
